---
- name: Database servers
  hosts: appdbs
  gather_facts: false
  roles:
    - common
  post_tasks:
    - name: Ensure portgresql is the installed/latest
      become: yes
      yum:
        name: postgresql-server
        state: latest
      tags:
        - postgresql
        - database
    # Need to check if postgresql has been initialized
    # If not, do initdb and create file
    - name: Check if postgresql has been initialized
      stat:
        path: /var/lib/pgsql/data/postgresql.conf
      register: postgresqlinit
      tags:
        - postgresql
        - database
    - name: Initiate postgresql database
      become: yes
      command: service postgresql initdb
               creates=/var/lib/pgsql/data/postgresql.conf
      when: postgresqlinit.stat.exists == false
      tags:
        - postgresql
        - database
    - name: Ensure postgresql is enabled at boot and started
      become: yes
      service:
        name: postgresql
        state: started
        enabled: yes
      tags:
        - postgresql
        - database
...
